import React from "react";
import imagen from "./Image/children-normassaludd.png";

const ProgramaAyuda = () => {
	return (
		<div>
			<h1>🎮 Support program for children with cancer.</h1>
			<p>
				In all these years of experience in the sector, we have found multiple
				cases of children from low-income families with cancer who face major
				problems, such as delays in carrying out consultations, diagnostic
				tests, among others, due to administrative procedures. This delays the
				start of timely cancer treatment in these children. Specialized
				consultations or private examinations are expensive and a family without
				resources will not be able to pay for these services in a private way.
				That forces them to wait until the authorizations are generated by the
				insurer and their availability. That is why at NormasSalud we have all
				the determination to help these children and we will do so by allocating
				a percentage of the token to this beautiful cause. With your support we
				will help to generate changes in the lives of many families who really
				need it. . We invite you to look at the complete information in the
				following 👉 White Paper.
			</p>
			<img src={imagen} alt="" />
		</div>
	);
};

export default ProgramaAyuda;
